MuPDF: replace https:// repository address with git://
Build server fails to fetch code via HTTPS:

    Submodule 'libmupdf' (https://git.ghostscript.com/mupdf.git) registered for path 'libmupdf'
    Cloning into 'libmupdf'...
    error: Unable to get pack file https://git.ghostscript.com/mupdf.git/objects/pack/pack-1be28dd0f46a60c2b76c8703eba71255e471b17c.pack
    GnuTLS recv error (-9): A TLS packet with unexpected length was received.
    error: Unable to find b5a8de69527cd27cc89ee1e1c3ffdf6f3eccd4ac under https://git.ghostscript.com/mupdf.git
    Cannot obtain needed object b5a8de69527cd27cc89ee1e1c3ffdf6f3eccd4ac
    while processing commit bc5284fb524de5f252da31f6d2ea68b1629bd35b.
    error: fetch failed.
    Clone of 'https://git.ghostscript.com/mupdf.git' into submodule path 'libmupdf' failed