Fix Status.im 1.13.0 build
For some incomprehensible reason it fails with:
```
error: creating directory '/tmp/tmp-status-react-896b583da/nix-shell-900-0': Permission denied
```
https://monitor.f-droid.org/builds/log/im.status.ethereum/2021042608

Since `/tmp` should always have `1777` permisions this should not
happen, but since it does I'm adding this dirty hack to the config.

Signed-off-by: Jakub Sokołowski <jakub@status.im>