Nextcloud dev: disable 20170907
src/main/java/com/owncloud/android/ui/fragment/OCFileListFragment.java:1431: error: constructor ToggleFavoriteOperation in class ToggleFavoriteOperation cannot be applied to given types;
            ToggleFavoriteOperation toggleFavoriteOperation = new ToggleFavoriteOperation(event.shouldFavorite,
                                                              ^
  required: boolean,String,String
  found: boolean,String
  reason: actual and formal argument lists differ in length